version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "KickstarterLambdas"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rrsgknsg5p1k"
s3_prefix = "KickstarterLambdas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
