version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ALambdaFunction"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rrsgknsg5p1k"
s3_prefix = "ALambdaFunction"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
